<?php

namespace app\index\controller;

use think\Controller;
use think\Db;
use think\Exception;
use think\Request;

class Orders extends Controller
{
    public $code;
    public  $model;
    public $validate;
    public function __construct(Request $request = null)
    {
        parent::__construct($request);
        $this->code=config('code');
        $this->model=model('Orders');
    }
    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
    }

    public function index()
    {
        $data =$this->request->get();
        if(!$data['typeorder']){
            $result= Db::table('orders')->where('uid',$data['uid'])->select();
            if($result){
                return json([
                    'code'=>200,
                    'msg'=>'数据获取成功',
                    'data'=>$result,
                ]);
            }else{
                return json([
                    'code'=>404,
                    'msg'=>'暂无数据',
                ]);
            }
        }else {
            $where = [];
            $where['uid']=$data['uid'];
            $where['status'] = $data['typeorder'];
            $result = Db::table('orders')->where($where)->select();
            if ($result) {
                return json([
                    'code' => 200,
                    'msg' => '数据获取成功',
                    'data' => $result,
                    'where' => $where
                ]);
            } else {
                return json([
                    'code' => 200,
                    'msg' => '暂无数据',
                ]);
            }
        }
    }

    /**
     * 显示创建资源表单页.
     *
     * @return \think\Response
     */
    public function create()
    {
        //
    }

    /**
     * 保存新建的资源
     *
     *添加未支付订单
     */
    public function save(Request $request)
    {
        $data = $this->request->post();
        $data['status']=1;
        $stayhomeModel = model('stayhome');
        $stayhome = $stayhomeModel->queryOne(['sid'=>$data['sid']],'status');
        if(!$stayhome['status']){
            return json([
                'code'=>200,
                'msg'=>'该名宿已被预定',
                'data'=>$stayhome
            ]);
        }
        Db::startTrans();
        try {
            $orderResult= $this->model->add($data);
            $lastid =$this->model->getLastInsID();
            $stayhomeResult= $stayhomeModel->edit(['status'=>0],['sid'=>$data['sid']]);
            if($stayhomeResult && $orderResult) {
                Db::commit();
                return json([
                    'code' => 200,
                    'msg' => '下单成功',
                    'oid' => $lastid,
                ]);
            }else{
                return json([
                    'code'=>200,
                    'msg'=>'下单失败',
                ]);
            }
        }catch (Exception $exception){
            Db::rollback();
            return json([
                'code'=>200,
                'msg'=>'下单失败',
            ]);

    }
    }

    /**
     * 显示指定的资源
     *
     * @param  int  $id
     * @return \think\Response
     */
    public function read($id)
    {
        //
    }

    /**
     * 显示编辑资源表单页.
     *
     * @param  int  $id
     * @return \think\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * 保存更新的资源
     *
     * @param  \think\Request  $request
     * @param  int  $id
     * @return \think\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * 删除指定资源
     *
     * @param  int  $id
     * @return \think\Response
     */
    public function delete($id)
    {
        //
    }
}
